onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

patchedDependencies:
  valaxy@0.25.11: patches/valaxy@0.25.11.patch
  valaxy-theme-press@0.25.11: patches/valaxy-theme-press@0.25.11.patch
