/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/configuration/': RouteRecordInfo<'/configuration/', '/configuration', Record<never, never>, Record<never, never>>,
    '/configuration/_example': RouteRecordInfo<'/configuration/_example', '/configuration/_example', Record<never, never>, Record<never, never>>,
    '/developer/': RouteRecordInfo<'/developer/', '/developer', Record<never, never>, Record<never, never>>,
    '/developer/api/': RouteRecordInfo<'/developer/api/', '/developer/api', Record<never, never>, Record<never, never>>,
    '/developer/api/_example': RouteRecordInfo<'/developer/api/_example', '/developer/api/_example', Record<never, never>, Record<never, never>>,
    '/faq/': RouteRecordInfo<'/faq/', '/faq', Record<never, never>, Record<never, never>>,
    '/faq/_example': RouteRecordInfo<'/faq/_example', '/faq/_example', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/advanced/': RouteRecordInfo<'/guide/advanced/', '/guide/advanced', Record<never, never>, Record<never, never>>,
    '/guide/advanced/_example': RouteRecordInfo<'/guide/advanced/_example', '/guide/advanced/_example', Record<never, never>, Record<never, never>>,
    '/guide/configuration': RouteRecordInfo<'/guide/configuration', '/guide/configuration', Record<never, never>, Record<never, never>>,
    '/guide/drivers/': RouteRecordInfo<'/guide/drivers/', '/guide/drivers', Record<never, never>, Record<never, never>>,
    '/guide/drivers/_example': RouteRecordInfo<'/guide/drivers/_example', '/guide/drivers/_example', Record<never, never>, Record<never, never>>,
    '/guide/drivers/local': RouteRecordInfo<'/guide/drivers/local', '/guide/drivers/local', Record<never, never>, Record<never, never>>,
    '/guide/installation/': RouteRecordInfo<'/guide/installation/', '/guide/installation', Record<never, never>, Record<never, never>>,
    '/guide/installation/containerized': RouteRecordInfo<'/guide/installation/containerized', '/guide/installation/containerized', Record<never, never>, Record<never, never>>,
    '/guide/installation/script': RouteRecordInfo<'/guide/installation/script', '/guide/installation/script', Record<never, never>, Record<never, never>>,
    '/guide/installation/source': RouteRecordInfo<'/guide/installation/source', '/guide/installation/source', Record<never, never>, Record<never, never>>,
    '/migration/': RouteRecordInfo<'/migration/', '/migration', Record<never, never>, Record<never, never>>,
    '/migration/alist-v3': RouteRecordInfo<'/migration/alist-v3', '/migration/alist-v3', Record<never, never>, Record<never, never>>,
  }
}
